### ISSUE TITLE
How to set payment option

### ISSUE THREAD

**Issue by Bandnakalra** [sunnysideup/silverstripe-ecommerce#35]
I have installed payment-paypal module, but I am getting error "No Payment Option Selected"
Please help me to fix it

**Comment by LABCAT** [comment]
Have you setup the required yml file containing your paypal details?

See the following example:
https://github.com/sunnysideup/silverstripe-payment_paypal/blob/master/_config/paypment_paypal.yml.example

**Comment by Bandnakalra** [comment]
After installing Paypal module just have to set up the yml file?? or have to make another changes??

**Comment by LABCAT** [comment]
You also need something like the following in your yml:

`EcommercePayment:
  supported_methods:
    PayPalExpressCheckoutPayment : "Credit Card (using Paypal)"`


Of course, you may have more than 1 payment you need to add here.

**Comment by Bandnakalra** [comment]
In config.yml??

**Comment by Bandnakalra** [comment]
Actually I am new to silverstripe :(

**Comment by Bandnakalra** [comment]
PHP Notice:  EcommercePayment::$supported_methods() requires an associative array.

I am getting this error

**Comment by LABCAT** [comment]
Here is an example:
https://github.com/sunnysideup/silverstripe-ecommerce/blob/master/_config/payment.yml

**Comment by Bandnakalra** [comment]
Ok Thank You :)
