### ISSUE TITLE
make the presentation of config settings more 

### ISSUE THREAD

**Issue by sunnysideup** [sunnysideup/silverstripe-ecommerce#43]
The configuration page for e-commerce would benefit to be more like this:

https://github.com/sunnysideup/silverstripe-site-wide-search/blob/master/src/Admin/SearchAdmin.php

A custom implementation of LeftAndMain to edit one record (perhaps there is a module out there that does this????)

**Comment by wilr** [comment]
@sunnysideup which configuration page? `EcommerceConfig` is YAML based right? Did you want these options to be configurable under SiteConfig > Store Settings or something?

**Comment by sunnysideup** [comment]
One sec.  I will add more detail here.  Sorry, I should have only added once I was done.
