### ISSUE TITLE
Product.php   getVersionedComponents is not SS3 compatible

### ISSUE THREAD

**Issue by sparkcom** [sunnysideup/silverstripe-ecommerce#9]
in getVersionedComponents method,

line 529,530

buildVersionSQL and buildDataObjectSet is deprecated already. 

any suggestion?

**Comment by sunnysideup** [comment]
Hi

Sorry that I never got back to you on this question!

Nicolaas

**Comment by sunnysideup** [comment]
I can help with sales prices, but I guess it it too late ;-(
